### ISSUE TITLE
`<mr-surface>` doesn't respect `rotation` and `position` attributes

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/MR.js#124] opened 2023-11-16 21:11 UTC
I assigned `rotation` and `position` parameters to a <mr-surface> element as follow

```
<mr-surface fixed="true" rotation="-30 0 0" position="0 -0.5 0">
```

This is what I see in the browser:
![image](https://github.com/Volumetrics-io/MR.js/assets/6750584/495ad38f-a9f1-4799-aeaa-7bc474e5ee3d)

In headset, the surface stays vertical, at the position 0, 0, 0

**Comment by lobau** [comment] 2023-11-16 21:12
Example at https://lastquestion-ly20.onrender.com/

**Comment by michaelthatsit** [comment] 2023-11-16 22:43
This is by design. `mr-surface` is meant to be positioned by the user. Even when fixed we're moving it to be positioned directly in front of the user as they enter XR. Thus it will always be overwritten.

You might be able to achieve the desired effect by applying your `position` and `rotation` value to `mr-container`.

**Comment by lobau** [comment] 2023-11-17 00:15
I see, sounds good, I will try this

**Closed** 2023-11-20 01:09 UTC
