### ISSUE TITLE
Static noise on play mode in XR 

### ISSUE THREAD

**Issue by Dinoel27** [Volumetrics-io/MR.js#126] opened 2023-11-16 22:08 UTC
I keep hearing static noise from Quest's speakers when playing the experience on XR 
Weird bug I think

**Comment by michaelthatsit** [comment] 2023-11-16 22:46
That is weird. we don't currently have audio integration so it could be something to do with your headset?

**Comment by Dinoel27** [comment] 2023-11-16 22:50
Could be could be 
I will check again

**Comment by michaelthatsit** [comment] 2023-11-20 03:55
Can't reproduce this so I'm closing it. I'm quite certain it's the fan in the headset. passthrough is expensive so the headset will warm up.

**Closed by michaelthatsit** 2023-11-20 03:55 UTC
